### ISSUE TITLE
Diagramas de casos de uso : Diagramas de secuencia de análisis

### ISSUE THREAD

**Issue by ANavarro96** [ANavarro96/notas-vv#13]
Hay dos casos de uso: "Enviar nota" y "Listar notas", que no tienen ningún diagrama de secuencia de análisis relacionado

**Comment by miguel-latre** [comment]
Debería haberse corregido en la memoria que habéis entregado.

**Comment by Luthmbj** [comment]
Solución: modificado diagrama de clases y añadidos los casos de uso en el apartado "Análisis"
