### ISSUE TITLE
Diagrama de casos de uso: Convenciones en algunos casos de uso

### ISSUE THREAD

**Issue by ANavarro96** [ANavarro96/notas-vv#16]
Hay casos de uso que no están escritos con un verbo en infinitivo, como "Por SMS" y "Por email"

**Comment by miguel-latre** [comment]
Puede entenderse que el nombre del caso de uso «Enviar nota» está implícito. De todas formas esto sería  obvio solo en el diagrama, pero no luego en las descripciones, donde sería más claro «Enviar nota por SMS» o «Enviar nota por email».
Podéis cerrar este defecto de todas formas con la etiqueta «wontfix».
