### ISSUE TITLE
Diagrama de clases: Funcionalidad repetida.

### ISSUE THREAD

**Issue by Gonzakick** [ANavarro96/notas-vv#18]
La clase Nota y Categoría poseen métodos comunes que podrían generalizarse.

**Comment by miguel-latre** [comment]
Además, ese cambio tendría implicaciones también en diseño (pares de clases CategoryList/Notepadv3, CategoryEdit/NoteEdit y parejas de métodos en la clase NotesDbAdapter.
Cerrad este defecto con la etiquta «wontfix», ya que como comentábamos en las tutorías de IS, el cambio implica mucho esfuerzo y poco beneficio, ya que la aplicación no se mantendrá ni evolucionará una vez acabado VV.
