### ISSUE TITLE
Diagrama de clases: Convención nombre de métodos y atributos.

### ISSUE THREAD

**Issue by Gonzakick** [ANavarro96/notas-vv#19]
Nombre de métodos y atributos más descriptivos y elección del idioma a utilizar en todo, en inglés o en español.

**Comment by miguel-latre** [comment]
No especificáis si nos nombres más descriptivos son en el análisis, el diseño o en ambos.
Comentadlo al cerrar este defecto y, si no lo modificáis en el trabajo, poned también la etiqueta «wontfix».

**Comment by Gonzakick** [comment]
En la etapa de análisis se usan nombres en español, excepto un método en inglés.
El otro error encontrado es en la clase Categoría en el método crear, se introduce un parámetro "título" y el atributo descriptivo de la clase Categoría debería ser 'título' no 'nombre'.
